### ISSUE TITLE
Find the way to integrate application with gmail api / ionic 

### ISSUE THREAD

**Issue by hson34** [s-p-a-r-k/Jacket-Tracker#30]
## Story/Task Details (Might need more than 1 person)
- [x] Research gmail/ionic mailing API requirements and details
- [x] Find the way to integrate application with gmail api 

Notes:
-Ionic email composer simply writes an email to be opened on the clients machine using their default mailing system
-Gmail API can send and compose emails from an authenticated gmail account
-Using Gmail API requires API key (application-level) or client auth token.
-Could try to use Firebase Authentication in place of API key (may have to enable Google account sign-in instead of email/password)

**Comment by gmcallister3** [comment]
Waiting on PR #49
