### ISSUE TITLE
Sending Email UI

### ISSUE THREAD

**Issue by s-p-a-r-k** [s-p-a-r-k/Jacket-Tracker#40]
## Story/Task Details
- [ ] Create UI that allows uniform lieutenants to choose between "send default email" and "send custom email"
- [ ] Create a template UI for "send custom email"

From quick management screen, display the email UI.
This will bring you to one page with a radio choosing between default or custom

**Comment by gmcallister3** [comment]
@s-p-a-r-k Split into UX issue and implementation issue
