### ISSUE TITLE
New uniform registration screen UI

### ISSUE THREAD

**Issue by scho300** [s-p-a-r-k/Jacket-Tracker#58]
## Story/Task Details
- [ ] Create UI so uniform lieutenants can enter information about new uniforms

Access from Add new uniform choice on flyout menu from logged in user.

**Comment by mtmarcus** [comment]
![20180201_125541 2](https://user-images.githubusercontent.com/2137913/38218717-9e570832-3687-11e8-85fd-1714355a80f1.jpg)

**Comment by mtmarcus** [comment]
I'll leave the error case which allows someone to override the uniform to the implementation team

**Comment by s-p-a-r-k** [comment]
![20180201_125744](https://user-images.githubusercontent.com/11774269/38219128-348fae7a-36a2-11e8-9291-0679bce9498e.jpg)

**Comment by s-p-a-r-k** [comment]
This is the UI screen actually, but you can use the screen above (without waiver)

**Comment by mtmarcus** [comment]
<img width="470" alt="screen shot 2018-04-19 at 5 01 24 pm" src="https://user-images.githubusercontent.com/2137913/39024128-a0b51f46-43f3-11e8-954c-ddb976c1bbcb.png">
